name: Terraform CI

on:
  pull_request:
    paths:
      - "terraform/**"

jobs:
  fmt_validate:
    name: Terraform Fmt and Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: terraform

      - name: Terraform Init
        run: terraform init -backend-config=./environments/dev/backend.tf
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

  plan:
    name: Terraform Plan
    needs: fmt_validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -backend-config=./environments/dev/backend.tf
        working-directory: terraform

      - name: Select workspace
        run: terraform workspace select dev || terraform workspace new dev
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -var-file=./environments/dev/terraform.tfvars
        working-directory: terraform
